### ISSUE TITLE
[FEATURE] 지출 카테고리 추가 UI + 기능 구현

### ISSUE THREAD

**Issue by hansh0101** [woowa-techcamp-2022/android-accountbook-01#13]
## 📝  To-do

- [x] 지출 카테고리 UI 구현
- [x] 지출 카테고리 기능 구현
- [x] Feature 관련 모듈 구현

## 📆 Date

0728 ~ 0728, 예상 소요시간 100분
