### ISSUE TITLE
[FEATURE] 내역 화면 UI + 기능 구현

### ISSUE THREAD

**Issue by hansh0101** [woowa-techcamp-2022/android-accountbook-01#15]
## 📝  To-do

- [x] 내역 화면 UI 구현
- [x] 내역 화면 기능 구현
- [x] 내역 Feature DI 모듈 구현

## 📆 Date

0729 ~ 0730, 예상 소요시간 60분
