### ISSUE TITLE
[FEATURE] 내역 등록 화면 UI + 기능 구현

### ISSUE THREAD

**Issue by hansh0101** [woowa-techcamp-2022/android-accountbook-01#17]
## 📝  To-do

- [x] 내역 등록 화면 UI 구현
- [x] 내역 등록 화면 기능 구현
- [x] 내역 등록 기능 관련 Feature 로직 구현

## 📆 Date

0730 ~ 0731
예상 소요시간: 210분
